# Generated by Django 3.0.6 on 2020-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200611_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume_dvigatel',
            field=models.IntegerField(choices=[(0.0, 0.0), (0.1, 0.1), (0.2, 0.2), (0.30000000000000004, 0.30000000000000004), (0.4, 0.4), (0.5, 0.5), (0.6000000000000001, 0.6000000000000001), (0.7000000000000001, 0.7000000000000001), (0.8, 0.8), (0.9, 0.9), (1.0, 1.0)], verbose_name='Объем двигателя'),
        ),
    ]
