# Generated by Django 3.0.6 on 2020-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200611_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume_dvigatel',
            field=models.IntegerField(verbose_name='Объем двигателя'),
        ),
    ]
