# Generated by Django 3.0.6 on 2020-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200611_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='volume_dvigatel',
        ),
    ]
