# Generated by Django 3.0.6 on 2020-06-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_car_volume_dvigatel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='volume_dvigatel',
        ),
    ]
