# Generated by Django 3.0.6 on 2020-06-18 12:31

from django.db import migrations, models
import django.db.models.deletion
import garage.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.CarBrand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_issue', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=garage.models.current_year, verbose_name='Год выпуска')),
                ('korobka', models.CharField(choices=[('auto', 'Автомат'), ('mech', 'Механика')], max_length=60, verbose_name='Коробка')),
                ('volume_dvigatel', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Объем двигателя')),
                ('probeg', models.IntegerField(verbose_name='Пробег')),
                ('car_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.CarBrand')),
                ('car_model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='car_marka', chained_model_field='car_marka', on_delete=django.db.models.deletion.CASCADE, to='garage.CarModel')),
            ],
        ),
    ]
