# Generated by Django 3.0.6 on 2020-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20200615_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume_dvigatel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Объем двигателя'),
        ),
    ]
